#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
polybar &
ksuperkey
feh --bg-fill --no-fehbg ~/.config/wallpaper.png
setxkbmap -option grp:alt_shift_toggle us,ru

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focus_follows_pointer true
bspc config focused_border_color "#FE8019"

bspc rule -a firefox desktop=^2 follow=on focus=on
bspc rule -a kitty desktop=^1 follow=on focus=on
bspc rule -a pavucontrol state=floating sticky=on
bspc rule -a Toolkit state=floating sticky=on
bspc rule -a steam desktop=^4 follow=off focus=off
bspc rule -a code deskop=^1 follow=on focus=on
bspc rule -a discord desktop=^3 follow=on focus=on
